//! Python bindings for AuthorTopic (the Author-Topic Model, Rosen-Zvi et al. 2004).
//!
//! `use super::*` pulls in the shared binding helpers (Corpus, build_corpus_from_docs,
//! save/load, array adapters, topic_words_helper, …).

use super::*;
use numpy::{PyArray1, PyArray2};
use pyo3::types::PyDict;
use rand_chacha::rand_core::SeedableRng;
use rand_chacha::ChaCha8Rng;
use std::collections::{BTreeSet, HashMap};

/// AuthorTopic: the Author-Topic Model (Rosen-Zvi, Griffiths, Steyvers & Smyth,
/// UAI 2004). Topics are conditioned on *authors*, not documents: each author has a
/// topic distribution, and a document's tokens are generated by drawing one of the
/// document's authors uniformly, then a topic from that author's distribution, then
/// a word. Answers "what does this author write about" and "which authors are close
/// in topic space", and handles multi-author documents. Collapsed Gibbs; LDA is the
/// special case of one unique author per document. Reference: gensim
/// ``AuthorTopicModel``.
#[pyclass(module = "topica")]
pub struct AuthorTopic {
    num_topics: usize,
    alpha: f64,
    beta: f64,
    seed: u64,
    fitted: bool,
    author_names: Vec<String>,
    topic_names: Vec<String>,
    model: Option<crate::author_topic::AuthorTopicModel>,
    corpus: Option<corpus::Corpus>,
}

#[derive(serde::Serialize, serde::Deserialize)]
struct AuthorTopicState {
    num_topics: usize,
    alpha: f64,
    beta: f64,
    seed: u64,
    fitted: bool,
    author_names: Vec<String>,
    topic_names: Vec<String>,
    corpus: Option<corpus::Corpus>,
    num_authors: Option<usize>,
    alpha_vec: Option<Vec<f64>>,
    alpha_sum: Option<f64>,
    topic_word: Option<Vec<Vec<f64>>>,
    doc_topic: Option<Vec<Vec<f64>>>,
    author_topic: Option<Vec<Vec<f64>>>,
    author_doc_counts: Option<Vec<u32>>,
    fit_history: Option<Vec<(usize, f64)>>,
    converged: Option<bool>,
}

impl AuthorTopic {
    fn fitted_model(&self) -> PyResult<&crate::author_topic::AuthorTopicModel> {
        self.model
            .as_ref()
            .ok_or_else(|| PyRuntimeError::new_err("model is not fitted yet; call fit() first"))
    }
}

#[pymethods]
impl AuthorTopic {
    /// The random seed the model was constructed with.
    #[getter]
    fn seed(&self) -> u64 {
        self.seed
    }

    /// Create an unfitted model. ``num_topics`` is the number of topics K.
    /// ``alpha`` is the symmetric author-topic Dirichlet concentration (default
    /// ``50/K``, the paper's value); ``beta`` is the symmetric topic-word Dirichlet
    /// (default 0.01, the paper's value). ``seed`` is the RNG seed.
    #[new]
    #[pyo3(signature = (num_topics, *, alpha=None, beta=0.01, seed=13))]
    fn new(
        #[pyo3(from_py_with = "py_num_topics")] num_topics: usize,
        alpha: Option<f64>,
        beta: f64,
        seed: u64,
    ) -> PyResult<Self> {
        if num_topics < 1 {
            return Err(PyValueError::new_err("num_topics must be >= 1"));
        }
        let alpha = alpha.unwrap_or(50.0 / num_topics as f64);
        if !(alpha.is_finite() && alpha > 0.0) {
            return Err(PyValueError::new_err("alpha must be finite and > 0"));
        }
        if !(beta.is_finite() && beta > 0.0) {
            return Err(PyValueError::new_err("beta must be finite and > 0"));
        }
        Ok(AuthorTopic {
            num_topics,
            alpha,
            beta,
            seed,
            fitted: false,
            author_names: Vec::new(),
            topic_names: Vec::new(),
            model: None,
            corpus: None,
        })
    }

    /// Constructor config as a JSON-serialisable dict (#400). ``authors`` is
    /// guidance data (supplied to ``fit``), not reported here.
    #[getter]
    fn settings<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyDict>> {
        let d = PyDict::new_bound(py);
        d.set_item("num_topics", self.num_topics)?;
        d.set_item("alpha", self.alpha)?;
        d.set_item("beta", self.beta)?;
        d.set_item("seed", self.seed)?;
        Ok(d)
    }

    /// Fit on `data` (a Corpus or a list of token lists) with `authors`: a list
    /// parallel to the documents, each entry the set of author labels for that
    /// document (>= 1 author; duplicates within a document are ignored). Author
    /// labels build a stable, sorted author vocabulary. `iters` is the number of
    /// collapsed-Gibbs sweeps (default 1000, a topica default — the paper uses
    /// problem-specific chain lengths).
    ///
    /// `progress` takes a ``(iteration, total, info)`` callback (see
    /// ``topica.progress``); pass ``True``/``False`` to force the bar on or off, and a
    /// ``KeyboardInterrupt`` raised from the callback aborts the fit.
    #[pyo3(signature = (data, authors, *, iters=1000, progress=None))]
    fn fit(
        mut slf: PyRefMut<'_, Self>,
        py: Python<'_>,
        data: &Bound<'_, PyAny>,
        authors: Vec<Vec<String>>,
        iters: usize,
        progress: Option<PyObject>,
    ) -> PyResult<Py<Self>> {
        // Build (or accept) the corpus; keep the surviving-document indices so the
        // author lists stay aligned when empty documents are pruned.
        let (corpus, kept, expected_len): (corpus::Corpus, Vec<usize>, usize) =
            if let Ok(c) = data.extract::<Corpus>() {
                let inner = c.inner;
                let n = inner.num_docs();
                (inner, (0..n).collect(), n)
            } else {
                let docs: Vec<Vec<String>> = data.extract().map_err(|_| {
                    PyValueError::new_err("fit() expects a Corpus or a list of token lists")
                })?;
                let orig = docs.len();
                let (cp, kept) = build_corpus_from_docs(
                    docs,
                    None,
                    None,
                    std::collections::HashSet::new(),
                    1,
                    1.0,
                    0,
                    0,
                )?;
                (cp, kept, orig)
            };
        if corpus.num_docs() == 0 {
            return Err(PyValueError::new_err("corpus contains no documents"));
        }
        if authors.len() != expected_len {
            return Err(PyValueError::new_err(format!(
                "authors has {} entries but there are {} documents",
                authors.len(),
                expected_len
            )));
        }

        // Realign author lists to the surviving documents.
        let doc_author_strs: Vec<Vec<String>> = kept.iter().map(|&i| authors[i].clone()).collect();

        // Stable, sorted author vocabulary.
        let mut set: BTreeSet<String> = BTreeSet::new();
        for a in &doc_author_strs {
            for name in a {
                set.insert(name.clone());
            }
        }
        let author_names: Vec<String> = set.into_iter().collect();
        let author_id: HashMap<&str, u32> = author_names
            .iter()
            .enumerate()
            .map(|(i, a)| (a.as_str(), i as u32))
            .collect();

        // Per-document author-id sets (deduped, non-empty).
        let mut doc_authors: Vec<Vec<u32>> = Vec::with_capacity(doc_author_strs.len());
        for (d, a) in doc_author_strs.iter().enumerate() {
            let mut seen: BTreeSet<u32> = BTreeSet::new();
            for name in a {
                seen.insert(author_id[name.as_str()]);
            }
            if seen.is_empty() {
                return Err(PyValueError::new_err(format!(
                    "document {d} has an empty author set; every document needs >= 1 author"
                )));
            }
            doc_authors.push(seen.into_iter().collect());
        }

        let num_authors = author_names.len();
        let num_types = corpus.num_types();
        let k = slf.num_topics;
        let alpha = vec![slf.alpha; k];
        let beta = slf.beta;
        let mut rng = ChaCha8Rng::seed_from_u64(slf.seed);

        let progress = resolve_progress(py, progress, "AuthorTopic")?;
        let (model, corpus) = py.allow_threads(move || {
            let mut on_progress = on_progress_bare(&progress);
            let m = crate::author_topic::fit(
                &corpus.docs,
                num_types,
                &doc_authors,
                num_authors,
                k,
                alpha,
                beta,
                iters,
                &mut on_progress,
                &mut rng,
            );
            (m, corpus)
        });
        reraise_if_interrupted(py)?;

        slf.model = Some(model);
        slf.corpus = Some(corpus);
        slf.author_names = author_names;
        slf.topic_names = (0..slf.num_topics).map(|i| format!("topic_{i}")).collect();
        slf.fitted = true;
        Ok(slf.into())
    }

    #[getter]
    fn num_topics(&self) -> usize {
        self.num_topics
    }

    /// Topic-word matrix φ (num_topics, vocab). Each row sums to 1.
    #[getter]
    fn topic_word<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyArray2<f64>>> {
        Ok(vecs_to_arr2(&self.fitted_model()?.topic_word).to_pyarray_bound(py))
    }

    /// Document-topic matrix θ_d (num_docs, num_topics): the empirical proportions of
    /// each document's sampled token→topic assignments in the terminal Gibbs draw
    /// (content-based, as in LDA — NOT the prior average of the document's authors'
    /// distributions). Each row sums to 1. This reflects the words a document actually
    /// contains; for the per-author mixtures see :attr:`author_topic`.
    #[getter]
    fn doc_topic<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyArray2<f64>>> {
        Ok(vecs_to_arr2(&self.fitted_model()?.doc_topic).to_pyarray_bound(py))
    }

    /// Author-topic matrix θ_a (num_authors, num_topics): each author's topic
    /// distribution, the model-defining output. Rows are ordered by
    /// :attr:`authors`. Each row sums to 1.
    #[getter]
    fn author_topic<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyArray2<f64>>> {
        Ok(vecs_to_arr2(&self.fitted_model()?.author_topic).to_pyarray_bound(py))
    }

    /// The author vocabulary (sorted), indexing the rows of :attr:`author_topic`.
    #[getter]
    fn authors(&self) -> PyResult<Vec<String>> {
        self.fitted_model()?;
        Ok(self.author_names.clone())
    }

    /// Number of documents each author appears on (length num_authors), aligned to
    /// :attr:`authors`. Report these alongside `author_topic`: an author's row is
    /// only as reliable as the documents behind it — a prolific author's row is
    /// pulled toward uniform by the alpha prior, while a one-document author's row is
    /// near-deterministic in that single document and unstable across seeds.
    #[getter]
    fn author_doc_counts<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyArray1<i64>>> {
        let c: Vec<i64> = self
            .fitted_model()?
            .author_doc_counts
            .iter()
            .map(|&x| x as i64)
            .collect();
        Ok(Array1::from(c).to_pyarray_bound(py))
    }

    #[getter]
    fn vocabulary(&self) -> PyResult<Vec<String>> {
        self.fitted_model()?;
        Ok(self.corpus.as_ref().unwrap().id_to_word.clone())
    }

    #[getter]
    fn topic_names(&self) -> PyResult<Vec<String>> {
        self.fitted_model()?;
        Ok(self.topic_names.clone())
    }
    #[setter]
    fn set_topic_names(&mut self, names: Vec<String>) -> PyResult<()> {
        if names.len() != self.num_topics {
            return Err(PyValueError::new_err(format!(
                "topic_names must have length {} (got {})",
                self.num_topics,
                names.len()
            )));
        }
        self.topic_names = names;
        Ok(())
    }

    #[getter]
    fn doc_names(&self) -> PyResult<Vec<String>> {
        self.fitted_model()?;
        Ok(self.corpus.as_ref().unwrap().doc_names.clone())
    }

    #[getter]
    fn fit_history(&self) -> PyResult<Vec<(usize, f64)>> {
        Ok(self.fitted_model()?.fit_history.clone())
    }

    /// :func:`topica.stop_reason` turns this flag into a plain-language summary of
    /// why the fit stopped (tolerance met, ``iters`` cap hit, or no early-stop
    /// criterion for this model).
    #[getter]
    fn converged(&self) -> PyResult<bool> {
        Ok(self.fitted_model()?.converged)
    }
    /// Alias of :attr:`converged` under the name that says what the flag means:
    /// True only if the fit early-stopped on `convergence_tol`; False when the
    /// full `iters` ran. `converged` is kept as an alias (issue #755).
    /// :func:`topica.stop_reason` turns this flag into a plain-language summary of
    /// why the fit stopped (tolerance met, ``iters`` cap hit, or no early-stop
    /// criterion for this model).
    #[getter]
    fn early_stopped(&self) -> PyResult<bool> {
        Ok(self.fitted_model()?.converged)
    }

    /// Top `n` words per topic (bare word strings). Pass ``weights=True`` for
    /// ``(word, φ)`` pairs.
    #[pyo3(signature = (n=10, *, topic=None, weights=false))]
    fn top_words<'py>(
        &self,
        py: Python<'py>,
        n: usize,
        topic: Option<usize>,
        weights: bool,
    ) -> PyResult<Bound<'py, PyAny>> {
        let phi = vecs_to_arr2(&self.fitted_model()?.topic_word);
        topic_words_helper(
            py,
            &phi,
            &self.corpus.as_ref().unwrap().id_to_word,
            self.num_topics,
            n,
            topic,
            weights,
        )
    }

    /// Top (author, probability) pairs for a topic, ranked by θ_a[topic]: the
    /// authors most associated with that topic.
    #[pyo3(signature = (topic, n=10))]
    fn top_authors(&self, topic: usize, n: usize) -> PyResult<Vec<(String, f64)>> {
        let m = self.fitted_model()?;
        if topic >= self.num_topics {
            return Err(PyValueError::new_err(format!(
                "topic {topic} out of range (num_topics={})",
                self.num_topics
            )));
        }
        let mut scored: Vec<(String, f64)> = self
            .author_names
            .iter()
            .enumerate()
            .map(|(a, name)| (name.clone(), m.author_topic[a][topic]))
            .collect();
        scored.sort_by(|x, y| y.1.partial_cmp(&x.1).unwrap());
        scored.truncate(n);
        Ok(scored)
    }

    /// Per-topic topic coherence, shape ``(num_topics,)``, aligned to topic index.
    /// Scores each topic's top-``n`` words. ``coherence_type`` selects the measure
    /// (``"u_mass"`` default, or ``"c_v"`` / ``"c_uci"`` / ``"c_npmi"``); ``texts``
    /// supplies the reference corpus for the windowed measures (defaults to the
    /// training corpus). Higher is more coherent (``u_mass`` is <= 0, nearer 0 is
    /// better; ``c_v`` in [0, 1]). Compare topics within one fit, not across corpora.
    #[pyo3(signature = (n=TopN(10), *, coherence_type="u_mass".to_string(), texts=None))]
    fn coherence<'py>(
        &self,
        py: Python<'py>,
        n: TopN,
        coherence_type: String,
        texts: Option<&Bound<'py, PyAny>>,
    ) -> PyResult<Bound<'py, PyArray1<f64>>> {
        let n = n.0;
        let phi = vecs_to_arr2(&self.fitted_model()?.topic_word);
        let tops = top_word_ids_phi(&phi, self.num_topics, n);
        coherence_dispatch(
            py,
            self.corpus.as_ref().unwrap(),
            &tops,
            n,
            &coherence_type,
            texts,
        )
    }

    /// Save the fitted model to `path` (topica's binary format).
    fn save(&self, path: &str) -> PyResult<()> {
        let m = self.fitted_model()?;
        write_state(
            path,
            MODEL_TAG_AUTHOR_TOPIC,
            &AuthorTopicState {
                num_topics: self.num_topics,
                alpha: self.alpha,
                beta: self.beta,
                seed: self.seed,
                fitted: self.fitted,
                author_names: self.author_names.clone(),
                topic_names: self.topic_names.clone(),
                corpus: self.corpus.clone(),
                num_authors: Some(m.num_authors),
                alpha_vec: Some(m.alpha.clone()),
                alpha_sum: Some(m.alpha_sum),
                topic_word: Some(m.topic_word.clone()),
                doc_topic: Some(m.doc_topic.clone()),
                author_topic: Some(m.author_topic.clone()),
                author_doc_counts: Some(m.author_doc_counts.clone()),
                fit_history: Some(m.fit_history.clone()),
                converged: Some(m.converged),
            },
        )
    }

    /// Load a model saved with [`save`].
    #[staticmethod]
    fn load(path: &str) -> PyResult<Self> {
        let s: AuthorTopicState = read_state(path, MODEL_TAG_AUTHOR_TOPIC)?;
        let model = if s.fitted {
            Some(crate::author_topic::AuthorTopicModel {
                num_topics: s.num_topics,
                num_authors: s.num_authors.unwrap_or(0),
                alpha: s.alpha_vec.unwrap_or_default(),
                alpha_sum: s.alpha_sum.unwrap_or(0.0),
                beta: s.beta,
                topic_word: s.topic_word.unwrap_or_default(),
                doc_topic: s.doc_topic.unwrap_or_default(),
                author_topic: s.author_topic.unwrap_or_default(),
                author_doc_counts: s.author_doc_counts.unwrap_or_default(),
                fit_history: s.fit_history.unwrap_or_default(),
                converged: s.converged.unwrap_or(false),
            })
        } else {
            None
        };
        Ok(AuthorTopic {
            num_topics: s.num_topics,
            alpha: s.alpha,
            beta: s.beta,
            seed: s.seed,
            fitted: s.fitted,
            author_names: s.author_names,
            topic_names: s.topic_names,
            model,
            corpus: s.corpus,
        })
    }

    fn __repr__(&self) -> String {
        format!(
            "AuthorTopic(num_topics={}, authors={}, fitted={})",
            self.num_topics,
            self.author_names.len(),
            self.fitted
        )
    }
}
