"""Committed gensim gold for topica AuthorTopic (#687).

The Author-Topic Model (Rosen-Zvi, Griffiths, Steyvers & Smyth, "The Author-Topic
Model for Authors and Documents," UAI 2004) extends LDA: each *author* has a topic
distribution, and a document's tokens are generated by first drawing one of the
document's authors uniformly, then a topic from that author's distribution, then a
word from that topic. LDA is the special case of one unique author per document.

Reference: gensim ``gensim.models.AuthorTopicModel`` (LGPL-2.1). LGPL is copyleft, so
topica implements collapsed Gibbs FROM THE PAPER (the paper's own inference method)
and uses gensim only as a black-box validation oracle here. gensim's inference is
variational, so parity is topic-aligned (Hungarian cosine on phi + author-topic
correlation), calibrated against gensim's own seed-to-seed floor -- never bit-exact.

We freeze, from a fixed-seed synthetic corpus with a planted author->topic block
structure (each author writes mostly about one topic; some documents are co-authored
so the author mixture matters):

  1. gensim's topic-word matrix phi (K, V) and per-author topic matrix theta (A, K)
     at TWO random_states -> a phi cosine + theta correlation self-consistency floor;
  2. the planted author->topic assignment, so topica's recovery can be checked
     directly (authors with distinct planted topics get distinct dominant topics).

Runs in CI WITHOUT gensim: the reference fit is frozen in the committed
``parity/author_topic_gold.npz`` + ``.json``.

    python parity/author_topic_gold.py --regenerate   # needs gensim
    python parity/author_topic_gold.py                # offline compare vs the gold
"""

from __future__ import annotations

import datetime
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import harness  # noqa: E402

NAME = "author_topic"

# --- planted synthetic corpus -------------------------------------------------
K = 3                    # topics
BLOCK = 8                # words per topic block
V = K * BLOCK            # vocabulary size
N_AUTHORS = 6            # 2 authors planted per topic
DOCS_PER_AUTHOR = 40     # single-author docs
N_COAUTHORED = 60        # extra 2-author docs (mixes two authors' topics)
DOC_LEN = 20
CORPUS_SEED = 271
PURITY = 0.75            # P(token drawn from author's own planted topic)
TOPIC_SPREAD = 0.15      # P(a topic-t draw emits a word from a DIFFERENT topic's
                         # block) -> breaks the word->topic bijection so phi rows
                         # genuinely overlap and the seed-to-seed floor is non-trivial

# gensim fit settings (deliberately short so the two seeds give a genuine,
# non-degenerate seed-to-seed floor rather than converging bit-identically)
G_PASSES = 15
G_ITERS = 20
ALPHA = 50.0 / K         # paper default (symmetric, sum 50)
ETA = 0.01               # paper default beta
GOLD_SEED = 20
FLOOR_SEED = 21


def _words_for_topic(t: int) -> list[str]:
    return [f"w{t * BLOCK + i}" for i in range(BLOCK)]


def planted_author_topic() -> np.ndarray:
    """Author a is planted on topic a // 2 (authors 0,1 -> t0; 2,3 -> t1; 4,5 -> t2)."""
    at = np.zeros((N_AUTHORS, K))
    for a in range(N_AUTHORS):
        at[a, a // 2] = 1.0
    return at


def build_corpus():
    """Return (docs, doc_authors, vocab, author_names, planted) deterministically.

    docs: list[list[str]]; doc_authors: list[list[str]] parallel to docs.
    """
    rng = np.random.default_rng(CORPUS_SEED)
    author_names = [f"a{a}" for a in range(N_AUTHORS)]
    planted = planted_author_topic()

    def author_topic(a: int) -> int:
        own = a // 2
        if rng.random() < PURITY:
            return own
        return int(rng.integers(0, K))

    docs: list[list[str]] = []
    doc_authors: list[list[str]] = []

    # Single-author documents.
    for a in range(N_AUTHORS):
        for _ in range(DOCS_PER_AUTHOR):
            toks = []
            for _ in range(DOC_LEN):
                t = author_topic(a)
                wt = t if rng.random() >= TOPIC_SPREAD else int(rng.integers(0, K))
                toks.append(_words_for_topic(wt)[int(rng.integers(0, BLOCK))])
            docs.append(toks)
            doc_authors.append([author_names[a]])

    # Co-authored documents: two distinct authors, token picks an author uniformly.
    for _ in range(N_COAUTHORED):
        a1, a2 = rng.choice(N_AUTHORS, size=2, replace=False)
        toks = []
        for _ in range(DOC_LEN):
            a = a1 if rng.random() < 0.5 else a2
            t = author_topic(int(a))
            wt = t if rng.random() >= TOPIC_SPREAD else int(rng.integers(0, K))
            toks.append(_words_for_topic(wt)[int(rng.integers(0, BLOCK))])
        docs.append(toks)
        doc_authors.append([author_names[int(a1)], author_names[int(a2)]])

    vocab = sorted({w for d in docs for w in d}, key=lambda w: int(w[1:]))
    return docs, doc_authors, vocab, author_names, planted


def _gensim_fit(docs, doc_authors, author_names, vocab, seed):
    """Fit gensim ATM; return (phi (K,V) over `vocab`, theta (A,K) over author_names)."""
    from gensim.corpora import Dictionary
    from gensim.models import AuthorTopicModel

    dictionary = Dictionary(docs)
    corpus = [dictionary.doc2bow(d) for d in docs]
    author2doc: dict[str, list[int]] = {a: [] for a in author_names}
    for di, auths in enumerate(doc_authors):
        for a in auths:
            author2doc[a].append(di)

    model = AuthorTopicModel(
        corpus=corpus,
        num_topics=K,
        id2word=dictionary,
        author2doc=author2doc,
        passes=G_PASSES,
        iterations=G_ITERS,
        alpha=ALPHA,
        eta=ETA,
        random_state=seed,
        eval_every=0,
    )

    # phi in `vocab` column order.
    topics = model.get_topics()  # (K, len(dictionary)) over dictionary ids
    col = np.zeros((K, V))
    for j, w in enumerate(vocab):
        if w in dictionary.token2id:
            col[:, j] = topics[:, dictionary.token2id[w]]
    col = col / col.sum(axis=1, keepdims=True)

    # theta per author in author_names order.
    theta = np.zeros((len(author_names), K))
    for ai, a in enumerate(author_names):
        for t, p in model.get_author_topics(a):
            theta[ai, t] = p
    return col, theta


def regenerate():
    docs, doc_authors, vocab, author_names, planted = build_corpus()
    phi, theta = _gensim_fit(docs, doc_authors, author_names, vocab, GOLD_SEED)
    phi2, theta2 = _gensim_fit(docs, doc_authors, author_names, vocab, FLOOR_SEED)

    # gensim seed-to-seed floor.
    floor_cos, _ = harness.align_cosine(phi, phi2)
    floor_theta_r = harness.doc_topic_correlation(theta, theta2)

    import gensim

    meta = {
        "model": "author_topic",
        "reference": "gensim.models.AuthorTopicModel",
        "gensim_version": gensim.__version__,
        "generated": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "K": K, "V": V, "n_authors": N_AUTHORS,
        "n_docs": len(docs),
        "alpha": ALPHA, "eta": ETA,
        "passes": G_PASSES, "iterations": G_ITERS,
        "gold_seed": GOLD_SEED, "floor_seed": FLOOR_SEED,
        "corpus_seed": CORPUS_SEED, "purity": PURITY,
        "vocab": vocab,
        "author_names": author_names,
        "docs": docs,
        "doc_authors": doc_authors,
        "floor_phi_cosine": float(floor_cos),
        "floor_theta_corr": float(floor_theta_r),
    }
    harness.save_gold(
        NAME,
        {"phi": phi, "theta": theta, "phi2": phi2, "theta2": theta2, "planted": planted},
        meta,
    )
    print(f"[{NAME}] wrote gold: gensim {gensim.__version__}, "
          f"K={K} A={N_AUTHORS} docs={len(docs)}")
    print(f"[{NAME}] gensim seed-to-seed floor: phi cosine={floor_cos:.3f}, "
          f"theta corr={floor_theta_r:.3f}")


def compare():
    """Offline: fit topica AuthorTopic on the SAME corpus and compare to the gold."""
    arrays, meta = harness.load_gold(NAME)
    phi_g = arrays["phi"]
    theta_g = arrays["theta"]
    planted = arrays["planted"]
    docs = meta["docs"]
    doc_authors = meta["doc_authors"]
    author_names = meta["author_names"]
    vocab = meta["vocab"]
    floor_cos = meta["floor_phi_cosine"]
    floor_theta = meta["floor_theta_corr"]

    try:
        import topica
    except ImportError:
        print(f"[{NAME}] topica not importable; skipping compare.")
        return

    if not hasattr(topica, "AuthorTopic"):
        print(f"[{NAME}] topica.AuthorTopic not built yet; gold is ready. Skipping.")
        return

    m = topica.AuthorTopic(K, alpha=meta["alpha"], beta=meta["eta"], seed=13).fit(
        docs, authors=doc_authors, iters=1000
    )

    # Map topica phi (K, its vocab) into gold `vocab` column order.
    tv = list(m.vocabulary)
    tv_idx = {w: i for i, w in enumerate(tv)}
    tw = np.asarray(m.topic_word)
    phi_t = np.zeros((K, len(vocab)))
    for j, w in enumerate(vocab):
        if w in tv_idx:
            phi_t[:, j] = tw[:, tv_idx[w]]
    phi_t = phi_t / phi_t.sum(axis=1, keepdims=True)

    # author theta in author_names order.
    ta = list(m.authors)
    ta_idx = {a: i for i, a in enumerate(ta)}
    at = np.asarray(m.author_topic)
    theta_t = np.zeros((len(author_names), K))
    for ai, a in enumerate(author_names):
        if a in ta_idx:
            theta_t[ai] = at[ta_idx[a]]

    # Align topica topics to the gold by the TOPIC-WORD (phi) matrix, and reuse that
    # SAME permutation for the author-topic (theta) correlation. The theta columns are
    # the same topics as phi, so a second, independent alignment (as a generic
    # doc_topic_correlation would do) could mask a phi/theta topic-labelling
    # disagreement. Enforcing the shared permutation is the real contract.
    cos, perm = harness.align_cosine(phi_t, phi_g)
    theta_t_aligned = theta_t[:, perm]
    per_topic = []
    for kk in range(K):
        a, b = theta_t_aligned[:, kk], theta_g[:, kk]
        if np.std(a) < 1e-12 or np.std(b) < 1e-12:
            continue
        per_topic.append(float(np.corrcoef(a, b)[0, 1]))
    theta_r = float(np.mean(per_topic)) if per_topic else float("nan")

    # planted recovery: each author's dominant topica topic, grouped by planted topic.
    planted_topic = planted.argmax(axis=1)
    dom = theta_t.argmax(axis=1)
    # authors sharing a planted topic should share a dominant topic; distinct planted
    # topics should map to distinct dominant topics.
    groups = {int(pt): set() for pt in planted_topic}
    for a in range(len(author_names)):
        groups[int(planted_topic[a])].add(int(dom[a]))
    clean = all(len(s) == 1 for s in groups.values())
    distinct = len({next(iter(s)) for s in groups.values()}) == len(groups)

    print(f"[{NAME}] phi aligned cosine   = {cos:.3f}  (gensim floor {floor_cos:.3f})")
    print(f"[{NAME}] theta corr (phi-perm)= {theta_r:.3f}  (gensim floor {floor_theta:.3f})")
    print(f"[{NAME}] planted recovery: clean-groups={clean} distinct-topics={distinct}")

    # Bars: phi within 0.05 of gensim's seed-to-seed cosine, author-topic correlation
    # >= 0.90 under the SAME topic permutation, and exact planted recovery.
    ok = cos >= floor_cos - 0.05 and theta_r >= 0.90 and clean and distinct
    print(f"[{NAME}] PARITY {'OK' if ok else 'CHECK'}")


if __name__ == "__main__":
    if "--regenerate" in sys.argv:
        regenerate()
    else:
        compare()
