"""HDBSCAN parity: topica's clusterer (petal-clustering) vs the reference
`hdbscan` package, on a FIXED embedding fixture (#489, last open item).

topica's Top2Vec reduces with UMAP and density-clusters with `petal-clustering`'s
HDBSCAN; the original `top2vec` package uses `umap-learn` + McInnes' `hdbscan`.
UMAP is stochastic and reducer-specific, so a whole-pipeline comparison cannot
tell a clustering *defect* from ordinary reducer variance. This check isolates the
clustering step: a frozen embedding fixture is handed to BOTH clusterers directly.

topica sees the fixture through ``Top2Vec(reducer="pca", n_components=D)``. PCA
with ``n_components >= D`` only mean-centers the rows (a pure translation), which
preserves every pairwise Euclidean distance, so petal's HDBSCAN clusters the
fixture geometry exactly. The reference gets the same matrix straight into
``hdbscan.HDBSCAN``. Everything matchable is matched: ``min_cluster_size``,
``min_samples``, euclidean metric, ``alpha=1``.

Finding (see the module docstring test): on well-separated structure the two
agree to ARI >= 0.99 and recover the planted truth identically. They diverge only
once the planted blobs overlap, and there BOTH degrade together (neither is
consistently closer to truth) — the disagreement is border-point / cluster-
selection variance (petal selects clusters by a bcubed+stability rule, the
reference by excess-of-mass), not a topica defect.

Skips cleanly when the reference `hdbscan` package is unavailable.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

# Frozen fixture (the well-separated, gated regime). Regenerated by --write.
FIXTURE_PATH = Path(__file__).with_name("top2vec_hdbscan_fixture.npz")

N_CLUSTERS = 4
N_PER = 60
DIM = 5  # top2vec's default reduced dimensionality (n_components=5)


def hdbscan_available() -> bool:
    try:
        import hdbscan  # noqa: F401
    except Exception:
        return False
    return True


def make_fixture(seed: int, sep: float, n_per: int = N_PER, dim: int = DIM):
    """Planted Gaussian blobs: ``N_CLUSTERS`` unit-variance clusters whose centers
    sit on a sphere of radius ``sep``. Larger ``sep`` = better separated. Fully
    determined by ``seed``/``sep`` so the fixture is reproducible."""
    rng = np.random.default_rng(seed)
    centers = rng.normal(size=(N_CLUSTERS, dim))
    centers = centers / np.linalg.norm(centers, axis=1, keepdims=True) * sep
    pts, truth = [], []
    for c in range(N_CLUSTERS):
        for _ in range(n_per):
            pts.append(centers[c] + rng.normal(size=dim))
            truth.append(c)
    return np.asarray(pts, dtype=np.float64), np.asarray(truth, dtype=np.int64)


def load_fixture():
    """The frozen well-separated fixture used for the pass gate."""
    if FIXTURE_PATH.exists():
        z = np.load(FIXTURE_PATH)
        return z["X"].astype(np.float64), z["truth"].astype(np.int64)
    # Fall back to the deterministic generator if the npz is absent.
    return make_fixture(seed=0, sep=8.0)


def topica_labels(X: np.ndarray, mcs: int, ms: int) -> np.ndarray:
    """Cluster ``X`` with topica (petal-clustering HDBSCAN via Top2Vec). PCA at
    full rank is distance-preserving, so this is petal HDBSCAN on ``X`` itself."""
    import topica

    dim = X.shape[1]
    docs = [["w"] for _ in range(len(X))]
    tv = topica.Top2Vec(
        reducer="pca",
        n_components=dim,
        min_cluster_size=mcs,
        min_samples=ms,
        diagnostics=False,
        seed=1,
    )
    tv.fit(docs, X)
    return np.asarray(tv.labels, dtype=np.int64)


def ref_labels(X: np.ndarray, mcs: int, ms: int) -> np.ndarray:
    """Cluster ``X`` with the reference `hdbscan` package."""
    import hdbscan

    model = hdbscan.HDBSCAN(
        min_cluster_size=mcs, min_samples=ms, metric="euclidean", alpha=1.0
    )
    return model.fit_predict(X).astype(np.int64)


def _ari(a: np.ndarray, b: np.ndarray) -> float:
    from sklearn.metrics import adjusted_rand_score

    return float(adjusted_rand_score(a, b))


def _nmi(a: np.ndarray, b: np.ndarray) -> float:
    from sklearn.metrics import normalized_mutual_info_score

    return float(normalized_mutual_info_score(a, b))


def run(mcs: int = 15, ms: int | None = None, verbose: bool = True) -> dict:
    """Pass-gate metrics on the frozen, well-separated fixture."""
    if ms is None:
        ms = mcs
    X, truth = load_fixture()
    t = topica_labels(X, mcs, ms)
    r = ref_labels(X, mcs, ms)
    m = {
        "cross_ari": _ari(t, r),
        "cross_nmi": _nmi(t, r),
        "topica_truth_ari": _ari(truth, t),
        "ref_truth_ari": _ari(truth, r),
        "topica_num_topics": int(len(set(t.tolist()) - {-1})),
        "ref_num_topics": int(len(set(r.tolist()) - {-1})),
        "topica_noise": int(np.sum(t == -1)),
        "ref_noise": int(np.sum(r == -1)),
        "min_cluster_size": mcs,
        "min_samples": ms,
    }
    if verbose:
        print("HDBSCAN parity (topica petal-clustering vs reference `hdbscan`)")
        print(f"  frozen fixture: {N_CLUSTERS} blobs x {N_PER} pts in {DIM}-D, well separated")
        for k, v in m.items():
            print(f"  {k:20} {v}")
    return m


def sweep(verbose: bool = True) -> list[dict]:
    """Full report across separation regimes: agreement is a function of how
    separable the planted structure is, not a fixed number."""
    rows = []
    for sep in (8.0, 4.0, 2.5):
        X, truth = make_fixture(seed=0, sep=sep)
        for mcs in (10, 15):
            t = topica_labels(X, mcs, mcs)
            r = ref_labels(X, mcs, mcs)
            row = {
                "sep": sep,
                "mcs": mcs,
                "cross_ari": _ari(t, r),
                "cross_nmi": _nmi(t, r),
                "topica_truth_ari": _ari(truth, t),
                "ref_truth_ari": _ari(truth, r),
                "topica_k": len(set(t.tolist()) - {-1}),
                "ref_k": len(set(r.tolist()) - {-1}),
                "topica_noise": int(np.sum(t == -1)),
                "ref_noise": int(np.sum(r == -1)),
            }
            rows.append(row)
            if verbose:
                print(
                    f"sep={sep:>4} mcs={mcs:>3} | topica k={row['topica_k']} "
                    f"noise={row['topica_noise']:>3} | ref k={row['ref_k']} "
                    f"noise={row['ref_noise']:>3} | ARI(t,r)={row['cross_ari']:.3f} "
                    f"NMI={row['cross_nmi']:.3f} | ARI(t,truth)={row['topica_truth_ari']:.3f} "
                    f"ARI(r,truth)={row['ref_truth_ari']:.3f}"
                )
    return rows


def _write_fixture() -> None:
    X, truth = make_fixture(seed=0, sep=8.0)
    np.savez_compressed(FIXTURE_PATH, X=X, truth=truth)
    print(f"wrote {FIXTURE_PATH} ({X.shape[0]} pts x {X.shape[1]}-D)")


if __name__ == "__main__":
    import sys

    if "--write" in sys.argv:
        _write_fixture()
    if not hdbscan_available():
        print("reference `hdbscan` not installed; skipping run")
        sys.exit(0)
    print("=== gated regime (frozen, well-separated) ===")
    run(verbose=True)
    print("\n=== separation sweep (report only) ===")
    sweep(verbose=True)
