//! Pachinko Allocation Model (Li & McCallum, "Pachinko Allocation: DAG-Structured
//! Mixture Models of Topic Correlations", ICML 2006) — the four-level / two-tier
//! version. Where LDA has a single layer of topics, PAM inserts an extra layer of
//! **super-topics** between the document and the topics, so correlations *between*
//! topics are modeled explicitly.
//!
//! The DAG has four levels: root → S super-topics → K sub-topics → words. Crucially
//! the sub-topics are **shared** across super-topics (this is a DAG, not a tree):
//! every super-topic can mix any of the K sub-topics, and two super-topics may
//! prefer overlapping or disjoint sub-topic sets. Each document `d` carries:
//!   - a multinomial over super-topics, `Dirichlet(alpha)` symmetric over S; and
//!   - for *each* super-topic `s`, a multinomial over sub-topics, drawn from a
//!     super-topic-specific Dirichlet with parameter vector `α_s = (α_{s1}..α_{sK})`.
//! Each sub-topic `k` is a multinomial over the vocabulary, `Dirichlet(beta)`.
//! A word token is generated by sampling a path: first a super-topic `s`, then a
//! sub-topic `k`, then a word `w ~ φ_k`.
//!
//! The **per-super-topic α_s vectors are the model's only globally shared link
//! between a super-topic and the sub-topics it prefers** — and are what give the
//! super-topics a stable identity across documents (without them the S
//! super-topics are exchangeable and never specialize). They are *initialized
//! asymmetrically* — super-topic `s` mildly prefers the slice of sub-topics around
//! `s·K/S`, which breaks the label symmetry — held fixed through a burn-in, then
//! **adapted to the data** (Li & McCallum §3, "we estimate α") by moment-matching
//! each α_s toward the super-topic's pooled sub-topic usage at a fixed total
//! concentration. Documents are also *committed* to a single random super-topic at
//! initialization, giving the super-topic layer something to specialize on.
//!
//! Inference is a **collapsed Gibbs sampler** over the per-token pair `g=(s,k)`,
//! integrating out the document multinomials and the topic-word multinomials
//! (Li & McCallum §3). Removing token (d, w)'s current pair, we draw
//!
//!   p(s,k) ∝ (n_ds + alpha)
//!            · (n_dsk + α_{sk}) / (n_ds + Σ_j α_{sj})
//!            · (n_kw  + beta)   / (n_k  + V·beta).
//!
//! The first factor is the document→super-topic term, the second the
//! super→sub-topic term (now with the estimated asymmetric prior), and the third
//! the sub-topic→word emission. (The document→super normalizer `n_d + S·alpha` is
//! constant across all (s,k) for a fixed token, so it cancels and is omitted here.)
//! We enumerate all S·K pairs and sample proportionally.
//!
//! Approximations: (a) the original paper also re-estimates the document→super
//! prior; we hold that symmetric and fixed at `alpha`, adapting only the
//! per-super-topic α_s sub-topic vectors. (b) Rather than the unconstrained Minka
//! Dirichlet-MLE (which, on the extremely sparse per-document sub-topic usage of
//! the four-level model, collapses α toward 0 and erases the super-topics' global
//! identity), we adapt α_s by fixed-concentration moment matching, which keeps the
//! prior informative and stable. The sampler is self-contained and deterministic
//! for a fixed `rng`.

use crate::estimator::{DirichletModel, Estimator, ModelFamily};
use rand::Rng;
use rand::SeedableRng;
use rand_pcg::Pcg64Mcg;
use rayon::prelude::*;

/// A fitted Pachinko Allocation model (four-level, two-tier).
pub struct PamModel {
    pub num_types: usize,         // V, vocabulary size
    pub num_super: usize,         // S, number of super-topics
    pub num_sub: usize,           // K, number of sub-topics
    pub alpha: f64,               // symmetric Dirichlet prior on the doc→super multinomial
    pub beta: f64,                // symmetric Dirichlet prior on the sub-topic→word multinomials
    pub alpha_sk: Vec<Vec<f64>>,  // S × K  estimated super→sub Dirichlet parameters
    pub nkw: Vec<Vec<u32>>,       // K × V  sub-topic ↦ word counts
    pub nk: Vec<u32>,             // K      sub-topic totals
    pub nds: Vec<Vec<u32>>,       // D × S  doc ↦ super-topic counts
    pub ndsk: Vec<Vec<Vec<u32>>>, // D × S × K  doc ↦ (super, sub) counts
    pub zs: Vec<Vec<usize>>,      // per-document token super-topic assignments
    pub zk: Vec<Vec<usize>>,      // per-document token sub-topic assignments
    /// Thinned θ draws (num_draws, D, K): sub-topic proportions marginalized
    /// over super-topics at each snapshot. Empty when draw_cap=0.
    pub theta_draws: Vec<Vec<Vec<f32>>>,
}

impl PamModel {
    pub fn num_super(&self) -> usize {
        self.num_super
    }

    pub fn num_sub(&self) -> usize {
        self.num_sub
    }

    /// Sub-topic word distributions φ_{k,w} = (n_{kw}+β)/(n_k+Vβ), shape K×V.
    /// Each row is a proper distribution over the vocabulary.
    pub fn topic_word(&self) -> Vec<Vec<f64>> {
        let v = self.num_types;
        self.nkw
            .iter()
            .zip(&self.nk)
            .map(|(row, &nk)| {
                let denom = nk as f64 + v as f64 * self.beta;
                row.iter()
                    .map(|&c| (c as f64 + self.beta) / denom)
                    .collect()
            })
            .collect()
    }

    /// Document ↦ sub-topic mixtures, shape D×K, marginalizing over super-topics.
    /// We take the smoothed marginal sub-topic count
    /// `θ_{d,k} ∝ (Σ_s n_{dsk}) + alpha` and normalize each row to sum to 1.
    pub fn doc_topic(&self) -> Vec<Vec<f64>> {
        let k = self.num_sub;
        self.ndsk
            .iter()
            .map(|doc| {
                let mut row = vec![0.0f64; k];
                for sub in 0..k {
                    let mut total = 0u32;
                    for s in 0..self.num_super {
                        total += doc[s][sub];
                    }
                    row[sub] = total as f64 + self.alpha;
                }
                let s: f64 = row.iter().sum();
                if s > 0.0 {
                    for x in row.iter_mut() {
                        *x /= s;
                    }
                }
                row
            })
            .collect()
    }

    /// Super-topic ↦ sub-topic association, shape S×K. Entry (s,k) is the smoothed
    /// posterior mean of the super→sub multinomial pooled over documents, using the
    /// estimated prior: `(Σ_d n_{dsk} + α_{sk}) / (Σ_d n_{ds} + Σ_j α_{sj})`.
    /// Reading a row tells you which sub-topics a super-topic groups together.
    pub fn super_sub(&self) -> Vec<Vec<f64>> {
        let s_count = self.num_super;
        let k = self.num_sub;
        let mut out = vec![vec![0.0f64; k]; s_count];
        for s in 0..s_count {
            let mut sk_totals = vec![0u32; k];
            let mut s_total = 0u32;
            for doc in &self.ndsk {
                for sub in 0..k {
                    sk_totals[sub] += doc[s][sub];
                    s_total += doc[s][sub];
                }
            }
            let alpha_sum: f64 = self.alpha_sk[s].iter().sum();
            let denom = s_total as f64 + alpha_sum;
            for sub in 0..k {
                out[s][sub] = (sk_totals[sub] as f64 + self.alpha_sk[s][sub]) / denom;
            }
        }
        out
    }

    /// Per-document super-topic proportions, shape D×S. Row `d` is the posterior
    /// mean of document `d`'s multinomial over super-topics, `θ^s_{d,s} ∝ n_{ds} +
    /// alpha`, normalized to sum to 1. This is the doc→super analogue of
    /// [`doc_topic`](Self::doc_topic) (which reports the doc→sub marginal): PAM's
    /// distinguishing structure is the per-document super-topic mixture, so a user
    /// doing correlation analysis reads it here. The smoothing uses `alpha`, which
    /// is exactly the symmetric Dirichlet prior on the doc→super multinomial (the
    /// factor-1 numerator in the Gibbs conditional), so this is the natural
    /// posterior mean rather than an output-only floor.
    pub fn doc_super(&self) -> Vec<Vec<f64>> {
        let s_count = self.num_super;
        self.nds
            .iter()
            .map(|doc| {
                let mut row: Vec<f64> = doc.iter().map(|&c| c as f64 + self.alpha).collect();
                let sum: f64 = row.iter().sum();
                if sum > 0.0 {
                    for x in row.iter_mut() {
                        *x /= sum;
                    }
                } else {
                    for x in row.iter_mut() {
                        *x = 1.0 / s_count as f64;
                    }
                }
                row
            })
            .collect()
    }
}

impl Estimator for PamModel {
    fn num_topics(&self) -> usize {
        self.num_sub
    }
    fn topic_word(&self) -> Vec<Vec<f64>> {
        PamModel::topic_word(self)
    }
    fn doc_topic(&self) -> Vec<Vec<f64>> {
        PamModel::doc_topic(self)
    }
    fn fit_history(&self) -> Vec<(usize, f64)> {
        Vec::new()
    }
    fn converged(&self) -> Option<bool> {
        None
    }
    fn model_family(&self) -> ModelFamily {
        ModelFamily::Dirichlet
    }
}

impl DirichletModel for PamModel {
    fn alpha(&self) -> Vec<f64> {
        vec![self.alpha; self.num_sub]
    }
    fn theta_draws(&self) -> Vec<Vec<Vec<f64>>> {
        self.theta_draws
            .iter()
            .map(|d| {
                d.iter()
                    .map(|r| r.iter().map(|&x| x as f64).collect())
                    .collect()
            })
            .collect()
    }
    fn doc_lengths(&self) -> Vec<usize> {
        self.zk.iter().map(|d| d.len()).collect()
    }
}

fn sample_index<R: Rng>(probs: &[f64], rng: &mut R) -> usize {
    let total: f64 = probs.iter().sum();
    let mut r = rng.gen::<f64>() * total;
    for (i, &p) in probs.iter().enumerate() {
        r -= p;
        if r <= 0.0 {
            return i;
        }
    }
    probs.len() - 1
}

/// One collapsed-Gibbs sweep over a contiguous slice of documents. Per-document
/// tables (`nds`, `ndsk`, `zs`, `zk`) are indexed 0-based within the slice and must
/// align with `docs`; the global sub-topic→word counts (`nkw`, `nk`) are the only
/// state shared across documents. `probs` is a reusable `S·K` scratch buffer. The
/// arithmetic and per-token RNG draw order are exactly those of the original
/// `PamModel::sweep`/`assign_token`, so the serial call site stays byte-identical.
#[allow(clippy::too_many_arguments)]
fn run_sweep_pam_range<R: Rng>(
    nds: &mut [Vec<u32>],
    ndsk: &mut [Vec<Vec<u32>>],
    zs: &mut [Vec<usize>],
    zk: &mut [Vec<usize>],
    nkw: &mut [Vec<u32>],
    nk: &mut [u32],
    docs: &[Vec<u32>],
    alpha_sk: &[Vec<f64>],
    alpha: f64,
    beta: f64,
    num_super: usize,
    num_sub: usize,
    num_types: usize,
    probs: &mut [f64],
    rng: &mut R,
) {
    let v = num_types;
    let s_count = num_super;
    let k = num_sub;
    for d in 0..docs.len() {
        let doc = &docs[d];
        for i in 0..doc.len() {
            let w = doc[i] as usize;
            let s_old = zs[d][i];
            let k_old = zk[d][i];
            nds[d][s_old] -= 1;
            ndsk[d][s_old][k_old] -= 1;
            nkw[k_old][w] -= 1;
            nk[k_old] -= 1;

            // The doc→super normalizer (n_d + S·alpha) cancels across pairs, but we
            // include it for clarity/numeric scaling.
            let n_d: u32 = nds[d].iter().sum();
            let super_norm = n_d as f64 + s_count as f64 * alpha;
            for s in 0..s_count {
                let nds_s = nds[d][s] as f64;
                let super_term = (nds_s + alpha) / super_norm;
                let alpha_sum: f64 = alpha_sk[s].iter().sum();
                let sub_norm = nds_s + alpha_sum;
                for sub in 0..k {
                    let sub_super = (ndsk[d][s][sub] as f64 + alpha_sk[s][sub]) / sub_norm;
                    let emit = (nkw[sub][w] as f64 + beta) / (nk[sub] as f64 + v as f64 * beta);
                    probs[s * k + sub] = super_term * sub_super * emit;
                }
            }

            let g = sample_index(probs, rng);
            let s = g / k;
            let sub = g % k;
            nds[d][s] += 1;
            ndsk[d][s][sub] += 1;
            nkw[sub][w] += 1;
            nk[sub] += 1;
            zs[d][i] = s;
            zk[d][i] = sub;
        }
    }
}

/// Contiguous, non-overlapping document ranges — one per worker (clamped so the
/// worker count never exceeds the document count). Mirrors the binding's
/// `partition_ranges`, kept local so the core stays self-contained.
fn partition_ranges(n: usize, parts: usize) -> Vec<(usize, usize)> {
    let parts = parts.max(1).min(n.max(1));
    let base = n / parts;
    let rem = n % parts;
    let mut ranges = Vec::with_capacity(parts);
    let mut start = 0;
    for i in 0..parts {
        let len = base + if i < rem { 1 } else { 0 };
        ranges.push((start, start + len));
        start += len;
    }
    ranges
}

/// One approximate-parallel (AD-LDA) sweep over the PAM count tables. Documents are
/// partitioned across workers; each worker samples its slice against a private clone
/// of the global `nkw`/`nk`, owning copies of its per-document `nds`/`ndsk`/`zs`/`zk`
/// slice (documents are disjoint), then the results are reconciled: `nkw` is the
/// exact additive merge `Σ_workers − (W−1)·original` (accumulated in `i64`, clamped
/// ≥ 0) and `nk` is **recomputed** from the merged `nkw` rows so
/// `nk[k] == Σ_w nkw[k][w]` holds exactly (no zero-clamp drift). Only the sub-topic
/// index of the sampled `(super, sub)` pair touches `nkw`, so word-token counts stay
/// conserved per worker and the standard AD-LDA merge applies unchanged. `alpha_sk`
/// is read-only during the sweep (it is adapted serially by `estimate_alpha_sk`
/// after the merge). Deterministic for a fixed `sweep_seed`/`num_threads`.
#[allow(clippy::too_many_arguments)]
fn parallel_sweep_pam(
    nds: &mut [Vec<u32>],
    ndsk: &mut [Vec<Vec<u32>>],
    zs: &mut [Vec<usize>],
    zk: &mut [Vec<usize>],
    nkw: &mut [Vec<u32>],
    nk: &mut [u32],
    docs: &[Vec<u32>],
    alpha_sk: &[Vec<f64>],
    alpha: f64,
    beta: f64,
    num_super: usize,
    num_sub: usize,
    num_types: usize,
    num_threads: usize,
    sweep_seed: u64,
) {
    struct PamWorkerOut {
        nkw: Vec<Vec<u32>>,
        nds: Vec<Vec<u32>>,
        ndsk: Vec<Vec<Vec<u32>>>,
        zs: Vec<Vec<usize>>,
        zk: Vec<Vec<usize>>,
        start: usize,
    }

    let v = num_types;
    let k = num_sub;
    let ranges = partition_ranges(docs.len(), num_threads);
    let orig_nkw = nkw.to_vec();
    let orig_nk = nk.to_vec();
    // Read-only views so workers can copy their slices inside the parallel map.
    let nds_ro: &[Vec<u32>] = nds;
    let ndsk_ro: &[Vec<Vec<u32>>] = ndsk;
    let zs_ro: &[Vec<usize>] = zs;
    let zk_ro: &[Vec<usize>] = zk;

    let outs: Vec<PamWorkerOut> = ranges
        .par_iter()
        .enumerate()
        .map(|(wid, &(start, end))| {
            let mut wnkw = orig_nkw.clone();
            let mut wnk = orig_nk.clone();
            let mut wnds: Vec<Vec<u32>> = nds_ro[start..end].to_vec();
            let mut wndsk: Vec<Vec<Vec<u32>>> = ndsk_ro[start..end].to_vec();
            let mut wzs: Vec<Vec<usize>> = zs_ro[start..end].to_vec();
            let mut wzk: Vec<Vec<usize>> = zk_ro[start..end].to_vec();
            let mut rng = Pcg64Mcg::seed_from_u64(
                sweep_seed ^ (wid as u64).wrapping_mul(0x9E37_79B9_7F4A_7C15),
            );
            let mut probs = vec![0.0f64; num_super * num_sub];
            run_sweep_pam_range(
                &mut wnds,
                &mut wndsk,
                &mut wzs,
                &mut wzk,
                &mut wnkw,
                &mut wnk,
                &docs[start..end],
                alpha_sk,
                alpha,
                beta,
                num_super,
                num_sub,
                num_types,
                &mut probs,
                &mut rng,
            );
            PamWorkerOut {
                nkw: wnkw,
                nds: wnds,
                ndsk: wndsk,
                zs: wzs,
                zk: wzk,
                start,
            }
        })
        .collect();

    // --- Reconcile nkw: final = Σ_workers − (W−1)·original, clamped ≥ 0. ---
    let wm1 = (outs.len() as i64) - 1;
    for t in 0..k {
        for w in 0..v {
            let sum_w: i64 = outs.iter().map(|o| o.nkw[t][w] as i64).sum();
            let val = sum_w - wm1 * orig_nkw[t][w] as i64;
            nkw[t][w] = val.max(0) as u32;
        }
        // Recompute nk from the merged nkw row so the two stay exactly consistent.
        nk[t] = nkw[t].iter().map(|&c| c as u64).sum::<u64>() as u32;
    }

    // --- Write back each worker's per-document slices (documents are disjoint). ---
    for out in outs {
        let start = out.start;
        for (i, (((ndsr, ndskr), zsr), zkr)) in out
            .nds
            .into_iter()
            .zip(out.ndsk)
            .zip(out.zs)
            .zip(out.zk)
            .enumerate()
        {
            nds[start + i] = ndsr;
            ndsk[start + i] = ndskr;
            zs[start + i] = zsr;
            zk[start + i] = zkr;
        }
    }
}

impl PamModel {
    /// One full Gibbs sweep over every token, delegating to the shared, range-based
    /// [`run_sweep_pam_range`] over the whole corpus. Disjoint `&mut self.field`
    /// borrows in a single call are permitted, so a single copy of the sampling
    /// logic is used by both the serial path and each AD-LDA worker (no drift).
    fn sweep<R: Rng>(&mut self, docs: &[Vec<u32>], rng: &mut R) {
        let mut probs = vec![0.0f64; self.num_super * self.num_sub];
        run_sweep_pam_range(
            &mut self.nds,
            &mut self.ndsk,
            &mut self.zs,
            &mut self.zk,
            &mut self.nkw,
            &mut self.nk,
            docs,
            &self.alpha_sk,
            self.alpha,
            self.beta,
            self.num_super,
            self.num_sub,
            self.num_types,
            &mut probs,
            rng,
        );
    }

    /// Re-estimate each super-topic's asymmetric sub-topic prior `α_s` by moment
    /// matching its *direction* to the pooled super→sub usage, at a fixed total
    /// concentration `conc = K·alpha·CONC_SCALE`. For super-topic `s` we form the
    /// smoothed pooled distribution
    ///   p_{sk} = (Σ_d n_{dsk} + α_{sk}) / (Σ_d n_{ds} + Σ_j α_{sj})
    /// and set α_{sk} ← conc · p_{sk}. Holding the concentration fixed (rather than
    /// running the unconstrained Minka MLE, which on this very sparse per-document
    /// usage collapses α toward 0 and erases the super-topics' global identity)
    /// keeps the prior informative and lets each super-topic *keep* a stable
    /// preference for the sub-topics it has come to own, sharpening it toward the
    /// data. This is the form of α-adaptation that gives PAM its correlated-topic
    /// structure; the unconstrained MLE is the "approximation we avoid" noted up top.
    fn estimate_alpha_sk(&mut self) {
        const CONC_SCALE: f64 = 4.0;
        let k = self.num_sub;
        let conc = k as f64 * self.alpha * CONC_SCALE;
        let ss = self.super_sub(); // pooled, smoothed super→sub distributions
        for (s, p) in ss.iter().enumerate() {
            let psum: f64 = p.iter().sum();
            if psum <= 0.0 {
                continue;
            }
            for sub in 0..k {
                self.alpha_sk[s][sub] = (conc * p[sub] / psum).max(1e-3);
            }
        }
    }
}

impl PamModel {
    /// Collapsed Gibbs log-likelihood for PAM marginalizing over super-topics.
    /// Uses the sub-topic document counts summed over super-topics and the
    /// sub-topic word counts, matching the marginal LDA-style formula.
    pub fn log_likelihood(&self, docs: &[Vec<u32>]) -> f64 {
        use crate::optimize::digamma;
        let k = self.num_sub;
        let v = self.num_types;
        let k_alpha = k as f64 * self.alpha;
        let v_beta = v as f64 * self.beta;
        let mut ll = 0.0f64;

        // Document-topic (marginal sub-topic) contribution.
        for (d, doc) in docs.iter().enumerate() {
            let n_d = doc.len() as f64;
            for sub in 0..k {
                let n_dk: u32 = (0..self.num_super).map(|s| self.ndsk[d][s][sub]).sum();
                let n_dk = n_dk as f64;
                if n_dk > 0.0 {
                    ll += digamma(self.alpha + n_dk) - digamma(self.alpha);
                }
            }
            ll -= digamma(k_alpha + n_d) - digamma(k_alpha);
        }

        // Sub-topic word contribution.
        for sub in 0..k {
            for w in 0..v {
                let n_kw = self.nkw[sub][w] as f64;
                if n_kw > 0.0 {
                    ll += digamma(self.beta + n_kw) - digamma(self.beta);
                }
            }
            ll -= digamma(v_beta + self.nk[sub] as f64) - digamma(v_beta);
        }

        ll
    }
}

/// Fit a Pachinko Allocation model by collapsed Gibbs sampling. Each document is
/// committed to a single random super-topic at initialization (with random
/// sub-topics per token); the model is then refined by `iters` Gibbs sweeps. The
/// per-super-topic sub-topic priors `α_s` start asymmetric (to break the
/// super-topic label symmetry), are held fixed through a burn-in, then adapted to
/// the data over the final quarter of the sweeps. Deterministic for a fixed `rng`.
#[allow(clippy::too_many_arguments)]
pub fn fit_pam<R: Rng>(
    docs: &[Vec<u32>],
    num_types: usize,
    num_super: usize,
    num_sub: usize,
    alpha: f64,
    beta: f64,
    iters: usize,
    rng: &mut R,
) -> PamModel {
    // Plain fit is the draw-collecting fit with collection disabled, so the
    // sampler lives in exactly one place (see `fit_pam_with_draws`).
    let (model, _, _) = fit_pam_with_draws(
        docs,
        num_types,
        num_super,
        num_sub,
        alpha,
        beta,
        iters,
        crate::keyatm::ThetaDrawOpts::new(false, 0, 0),
        0.0,
        0,
        1,
        rng,
    );
    model
}

/// Fit a PAM with thinned θ snapshots (sub-topic proportions, marginalized over
/// super-topics) collected every `thin` sweeps, ring-buffered to `cap` draws.
/// `cap=0` disables collection entirely.
///
/// `num_threads` selects the sampler: `1` (or `0`) runs the exact serial sweep,
/// byte-identical to the pre-threading path; `>1` runs MALLET-style
/// approximate-parallel (AD-LDA) sampling, deterministic for a fixed
/// `num_threads` + seed.
///
/// Returns `(model, ll_history, converged)`.
#[allow(clippy::too_many_arguments)]
pub fn fit_pam_with_draws<R: Rng>(
    docs: &[Vec<u32>],
    num_types: usize,
    num_super: usize,
    num_sub: usize,
    alpha: f64,
    beta: f64,
    iters: usize,
    opts: crate::keyatm::ThetaDrawOpts,
    convergence_tol: f64,
    check_every: usize,
    num_threads: usize,
    rng: &mut R,
) -> (PamModel, Vec<(usize, f64)>, bool) {
    let d = docs.len();
    let k = num_sub;

    // Break the super-topic label symmetry with a structured prior: super-topic
    // `s` mildly prefers the contiguous slice of sub-topics around `s·K/S`. This
    // only biases which super-topic owns which sub-topic slots; the sub-topic to
    // vocabulary mapping is still learned, and the asymmetric-alpha re-estimate
    // can move the preference. Without it the super-topics stay exchangeable and
    // never specialize.
    let alpha_sk: Vec<Vec<f64>> = (0..num_super)
        .map(|s| {
            (0..num_sub)
                .map(|kk| {
                    let owner = (kk * num_super) / num_sub;
                    if owner == s {
                        alpha * 5.0
                    } else {
                        alpha
                    }
                })
                .collect()
        })
        .collect();
    let mut model = PamModel {
        num_types,
        num_super,
        num_sub,
        alpha,
        beta,
        alpha_sk,
        nkw: vec![vec![0u32; num_types]; num_sub],
        nk: vec![0u32; num_sub],
        nds: vec![vec![0u32; num_super]; d],
        ndsk: vec![vec![vec![0u32; num_sub]; num_super]; d],
        zs: docs.iter().map(|doc| vec![0usize; doc.len()]).collect(),
        zk: docs.iter().map(|doc| vec![0usize; doc.len()]).collect(),
        theta_draws: Vec::new(),
    };

    for (di, doc) in docs.iter().enumerate() {
        let s = (rng.gen::<f64>() * num_super as f64) as usize % num_super;
        for (i, &w) in doc.iter().enumerate() {
            let w = w as usize;
            let sub = (rng.gen::<f64>() * num_sub as f64) as usize % num_sub;
            model.nds[di][s] += 1;
            model.ndsk[di][s][sub] += 1;
            model.nkw[sub][w] += 1;
            model.nk[sub] += 1;
            model.zs[di][i] = s;
            model.zk[di][i] = sub;
        }
    }

    let adapt_after = iters - iters / 4;
    let mut ll_history: Vec<(usize, f64)> = Vec::new();
    let mut converged = false;

    for it in 0..iters {
        if num_threads <= 1 {
            // Exact serial path — byte-identical to the pre-threading loop.
            model.sweep(docs, rng);
        } else {
            // Approximate-parallel AD-LDA. One per-sweep seed drawn from the main
            // RNG keeps it deterministic for a fixed num_threads + seed.
            let sweep_seed = rng.gen::<u64>();
            parallel_sweep_pam(
                &mut model.nds,
                &mut model.ndsk,
                &mut model.zs,
                &mut model.zk,
                &mut model.nkw,
                &mut model.nk,
                docs,
                &model.alpha_sk,
                model.alpha,
                model.beta,
                model.num_super,
                model.num_sub,
                model.num_types,
                num_threads,
                sweep_seed,
            );
        }
        if it >= adapt_after {
            model.estimate_alpha_sk();
        }
        let iter = it + 1;
        if opts.thin > 0 && iter % opts.thin == 0 {
            let snap: Vec<Vec<f32>> = model
                .ndsk
                .iter()
                .map(|doc| {
                    let mut row = vec![0.0f64; k];
                    for sub in 0..k {
                        let total: u32 = (0..model.num_super).map(|s| doc[s][sub]).sum();
                        row[sub] = total as f64 + model.alpha;
                    }
                    let s: f64 = row.iter().sum();
                    row.iter()
                        .map(|&x| (if s > 0.0 { x / s } else { 1.0 / k as f64 }) as f32)
                        .collect()
                })
                .collect();
            // Ring buffer of theta snapshots; cap == 0 disables collection. Guard
            // the pop so an empty buffer can never underflow on remove(0) (#497):
            // ThetaDrawOpts::new forces thin == 0 when cap == 0, so this is a
            // defensive invariant rather than a live path.
            if opts.cap > 0 {
                if model.theta_draws.len() >= opts.cap {
                    model.theta_draws.remove(0);
                }
                model.theta_draws.push(snap);
            }
        }
        // Trace recording and optional convergence check (never alters RNG).
        if check_every > 0 && iter % check_every == 0 {
            let ll = model.log_likelihood(docs);
            ll_history.push((iter, ll));
            if convergence_tol > 0.0 && ll_history.len() >= 2 {
                let prev = ll_history[ll_history.len() - 2].1;
                let rel = (ll - prev).abs() / (prev.abs() + 1e-12);
                if rel < convergence_tol {
                    converged = true;
                    break;
                }
            }
        }
    }

    (model, ll_history, converged)
}

#[cfg(test)]
mod tests {
    use super::*;
    use rand_chacha::rand_core::SeedableRng;
    use rand_chacha::ChaCha8Rng;

    /// Build a corpus with K=4 disjoint-vocabulary sub-topic blocks grouped into
    /// S=2 super-topics: super-topic 0 owns blocks {0,1}, super-topic 1 owns
    /// blocks {2,3}. Each document draws from BOTH blocks of ONE super-topic, so
    /// the two sub-topics inside a super-topic co-occur (but never cross between
    /// super-topics). The block mixing ratio varies per document so the two
    /// always-co-occurring sub-topics stay individually identifiable. Flat LDA
    /// would see four topics with no notion of the grouping; PAM should recover
    /// both the blocks and the grouping.
    fn planted_corpus() -> (Vec<Vec<u32>>, Vec<Vec<u32>>, [[usize; 2]; 2], usize) {
        let blocks: Vec<Vec<u32>> = (0..4).map(|b| (b * 6..b * 6 + 6).collect()).collect();
        let v = 24;
        let groups = [[0usize, 1], [2, 3]]; // super-topic ↦ its two planted blocks
        let mut docs = Vec::new();
        for d in 0..400 {
            let g = d % 2; // which super-topic this document belongs to
            let pair = groups[g];
            let n0 = 8 + (d / 2) % 17; // 8..=24 tokens from the first block
            let n1 = 32 - n0; // the rest from the second block
            let mut doc = Vec::new();
            for t in 0..n0 {
                let blk = &blocks[pair[0]];
                doc.push(blk[(t + d) % blk.len()]);
            }
            for t in 0..n1 {
                let blk = &blocks[pair[1]];
                doc.push(blk[(t + d) % blk.len()]);
            }
            docs.push(doc);
        }
        (docs, blocks, groups, v)
    }

    #[test]
    fn recovers_planted_blocks_and_grouping() {
        let (docs, blocks, groups, v) = planted_corpus();
        let mut rng = ChaCha8Rng::seed_from_u64(42);
        let model = fit_pam(&docs, v, 2, 4, 0.1, 0.01, 200, &mut rng);

        // (1) Each sub-topic's top words concentrate on a single planted block.
        // Map each sub-topic to the block its top-6 words fill.
        let tw = model.topic_word();
        let mut sub_to_block = vec![usize::MAX; 4];
        for (k, row) in tw.iter().enumerate() {
            let mut idx: Vec<usize> = (0..v).collect();
            idx.sort_by(|&a, &b| row[b].partial_cmp(&row[a]).unwrap());
            let top: std::collections::HashSet<usize> = idx[..6].iter().copied().collect();
            for (bi, blk) in blocks.iter().enumerate() {
                if blk.iter().all(|&w| top.contains(&(w as usize))) {
                    sub_to_block[k] = bi;
                }
            }
            assert_ne!(
                sub_to_block[k],
                usize::MAX,
                "sub-topic {} top words do not fill a single planted block",
                k
            );
        }
        // All four blocks should be covered, one per sub-topic (a bijection).
        let covered: std::collections::HashSet<usize> = sub_to_block.iter().copied().collect();
        assert_eq!(
            covered.len(),
            4,
            "sub-topics did not recover all 4 blocks: {:?}",
            sub_to_block
        );

        // (2) The super_sub() matrix groups the co-occurring sub-topics. For each
        // super-topic take its top-2 sub-topics, translate to the blocks they
        // represent, and check they equal one planted group (match up to
        // permutation of super-topics).
        let ss = model.super_sub();
        let top2_blocks = |s: usize| -> std::collections::HashSet<usize> {
            let row = &ss[s];
            let mut idx: Vec<usize> = (0..4).collect();
            idx.sort_by(|&a, &b| row[b].partial_cmp(&row[a]).unwrap());
            idx[..2].iter().map(|&k| sub_to_block[k]).collect()
        };
        let recovered: Vec<std::collections::HashSet<usize>> = (0..2).map(top2_blocks).collect();
        let planted: Vec<std::collections::HashSet<usize>> =
            groups.iter().map(|g| g.iter().copied().collect()).collect();

        // Match super-topics to planted groups up to permutation.
        let matches = |perm: [usize; 2]| -> bool {
            recovered[0] == planted[perm[0]] && recovered[1] == planted[perm[1]]
        };
        assert!(
            matches([0, 1]) || matches([1, 0]),
            "super_sub grouping {:?} does not match planted groups {:?}",
            recovered,
            planted
        );
    }

    #[test]
    fn deterministic_for_fixed_seed() {
        let docs: Vec<Vec<u32>> = (0..50)
            .map(|d| (0..10).map(|i| ((i + d) % 12) as u32).collect())
            .collect();
        let mut r1 = ChaCha8Rng::seed_from_u64(7);
        let mut r2 = ChaCha8Rng::seed_from_u64(7);
        let m1 = fit_pam(&docs, 12, 2, 4, 0.1, 0.01, 30, &mut r1);
        let m2 = fit_pam(&docs, 12, 2, 4, 0.1, 0.01, 30, &mut r2);
        assert_eq!(m1.topic_word(), m2.topic_word());
    }

    #[test]
    fn pam_conforms() {
        let docs: Vec<Vec<u32>> = (0..40)
            .map(|d| (0..8).map(|i| ((i + d * 3) % 12) as u32).collect())
            .collect();
        let mut rng = ChaCha8Rng::seed_from_u64(11);
        let m = fit_pam(&docs, 12, 2, 3, 0.1, 0.01, 20, &mut rng);
        let base = crate::conformance::check_conformance(&m);
        assert!(base.is_empty(), "check_conformance: {:?}", base);
        let dir = crate::conformance::check_dirichlet(&m);
        assert!(dir.is_empty(), "check_dirichlet: {:?}", dir);
    }

    #[test]
    fn doc_super_rows_are_probabilities_over_supers() {
        // doc_super rows are per-document mixtures over super-topics: shape D×S,
        // non-negative, and sum to 1. The planted corpus splits documents by
        // super-topic (even/odd docs), so the dominant super-topic must partition
        // the corpus into two groups aligned (up to label swap) with the planting.
        let (docs, _, _, v) = planted_corpus();
        let mut rng = ChaCha8Rng::seed_from_u64(42);
        let model = fit_pam(&docs, v, 2, 4, 0.1, 0.01, 200, &mut rng);
        let ds = model.doc_super();
        assert_eq!(ds.len(), docs.len());
        for row in &ds {
            assert_eq!(row.len(), 2);
            assert!(row.iter().all(|&x| x >= 0.0));
            let sum: f64 = row.iter().sum();
            assert!((sum - 1.0).abs() < 1e-9, "row sums to {sum}, not 1");
        }
        // Dominant super-topic per doc vs the planted (d % 2) label, up to swap.
        let agree = ds
            .iter()
            .enumerate()
            .filter(|(d, row)| {
                let pred = if row[0] >= row[1] { 0 } else { 1 };
                pred == d % 2
            })
            .count() as f64
            / docs.len() as f64;
        let acc = agree.max(1.0 - agree);
        assert!(acc > 0.8, "doc_super super-topic recovery {acc:.2} too low");
    }

    #[test]
    fn theta_ring_buffer_no_underflow_on_degenerate_opts() {
        // Guard for #497: the θ-snapshot ring buffer must not call remove(0) on an
        // empty Vec. ThetaDrawOpts::new forces thin=0 when cap=0, so this pairing
        // is unreachable via the public constructor; construct it directly to lock
        // the defensive `cap > 0` guard against regression.
        let docs: Vec<Vec<u32>> = (0..20)
            .map(|d| (0..8).map(|i| ((i + d) % 12) as u32).collect())
            .collect();
        let opts = crate::keyatm::ThetaDrawOpts { cap: 0, thin: 1 };
        let mut rng = ChaCha8Rng::seed_from_u64(3);
        let (model, _, _) =
            fit_pam_with_draws(&docs, 12, 2, 3, 0.1, 0.01, 5, opts, 0.0, 0, 1, &mut rng);
        // Collection stays disabled: nothing pushed despite thin=1.
        assert!(model.theta_draws.is_empty());
    }

    /// Helper: a small corpus with enough documents to partition across workers.
    fn threading_corpus() -> (Vec<Vec<u32>>, usize) {
        let v = 16;
        let docs: Vec<Vec<u32>> = (0..60)
            .map(|d| (0..12).map(|i| ((i * 5 + d * 3) % v) as u32).collect())
            .collect();
        (docs, v)
    }

    fn fit_threaded(
        docs: &[Vec<u32>],
        v: usize,
        iters: usize,
        num_threads: usize,
        seed: u64,
    ) -> PamModel {
        let mut rng = ChaCha8Rng::seed_from_u64(seed);
        let opts = crate::keyatm::ThetaDrawOpts::new(false, 0, 0);
        let (m, _, _) = fit_pam_with_draws(
            docs,
            v,
            3,
            4,
            0.1,
            0.01,
            iters,
            opts,
            0.0,
            0,
            num_threads,
            &mut rng,
        );
        m
    }

    #[test]
    fn num_threads_one_is_bit_identical_to_serial() {
        // num_threads=1 must never draw the per-sweep seed and must reproduce the
        // pre-threading serial path exactly.
        let (docs, v) = threading_corpus();
        let mut r_serial = ChaCha8Rng::seed_from_u64(99);
        let serial = fit_pam(&docs, v, 3, 4, 0.1, 0.01, 40, &mut r_serial);
        let threaded1 = fit_threaded(&docs, v, 40, 1, 99);
        assert_eq!(serial.nkw, threaded1.nkw, "nkw differs at num_threads=1");
        assert_eq!(serial.nk, threaded1.nk, "nk differs at num_threads=1");
        assert_eq!(serial.zs, threaded1.zs, "zs differs at num_threads=1");
        assert_eq!(serial.zk, threaded1.zk, "zk differs at num_threads=1");
        assert_eq!(serial.nds, threaded1.nds, "nds differs at num_threads=1");
        assert_eq!(serial.ndsk, threaded1.ndsk, "ndsk differs at num_threads=1");
    }

    #[test]
    fn threaded_is_deterministic_for_fixed_threads_and_seed() {
        // A fixed num_threads>1 with a fixed seed reproduces exactly across runs.
        let (docs, v) = threading_corpus();
        let a = fit_threaded(&docs, v, 40, 4, 123);
        let b = fit_threaded(&docs, v, 40, 4, 123);
        assert_eq!(a.nkw, b.nkw);
        assert_eq!(a.nk, b.nk);
        assert_eq!(a.nds, b.nds);
        assert_eq!(a.ndsk, b.ndsk);
        assert_eq!(a.topic_word(), b.topic_word());
    }

    #[test]
    fn threaded_nk_matches_merged_nkw_and_token_total() {
        // The AD-LDA merge recomputes nk from the merged nkw rows, so nk[k] must
        // equal Σ_w nkw[k][w] exactly, and the grand total must equal the corpus
        // token count (no tokens lost or duplicated in the partition-and-merge).
        let (docs, v) = threading_corpus();
        let m = fit_threaded(&docs, v, 40, 4, 7);
        for t in 0..m.num_sub {
            let row_sum: u32 = m.nkw[t].iter().sum();
            assert_eq!(m.nk[t], row_sum, "nk[{t}] != Σ_w nkw[{t}][w]");
        }
        let total_tokens: usize = docs.iter().map(|d| d.len()).sum();
        let nk_total: u32 = m.nk.iter().sum();
        assert_eq!(nk_total as usize, total_tokens, "token count not conserved");
    }

    #[test]
    fn threaded_handles_more_workers_than_docs() {
        // partition_ranges clamps the worker count to the document count, so an
        // oversized num_threads must run cleanly without empty-chunk corruption.
        let docs: Vec<Vec<u32>> = (0..3)
            .map(|d| (0..6).map(|i| ((i + d) % 8) as u32).collect())
            .collect();
        let m = fit_threaded(&docs, 8, 20, 16, 5);
        let total_tokens: usize = docs.iter().map(|d| d.len()).sum();
        let nk_total: u32 = m.nk.iter().sum();
        assert_eq!(nk_total as usize, total_tokens);
    }
}
