"""General post-hoc topic-model diagnostics — compatibility shim (issue #757).

The implementations moved to :mod:`topica.select` (K/model selection),
:mod:`topica.inspect` (reading fitted topics), and :mod:`topica.evaluate`
(credibility diagnostics). This module re-exports every name it historically
exposed so ``topica.validation.X`` and ``from topica.validation import X`` keep
working. Prefer the workflow namespaces in new code.
"""

from __future__ import annotations

# Re-export the coherence helpers this module has always surfaced.
from .coherence import (  # noqa: F401
    _as_topic_word, _as_doc_topic, _vocabulary_of, _rbo, _ref_corpus,
    coherence as _coherence, exclusivity as _exclusivity,
)

from .select import (  # noqa: F401
    BestKExplanation,
    SEARCH_K_DIRECTIONS,
    SearchKResult,
    SelectModelResult,
    _SEARCH_K_CRITERIA,
    _SEARCH_K_DEFAULT_SEEDS,
    _aggregate_over_seeds,
    _argbest_k,
    _cao_juan,
    _deveaud,
    _extra_criterion,
    _frontier_score,
    _mean_exclusivity,
    _resolve_workers,
    plot_models,
    plot_search_k,
    plot_topic_discovery,
    quality_frontier,
    search_k,
    select_model,
)

from .inspect import (  # noqa: F401
    PyLDAvisInputs,
    TopicCorrelation,
    TopicLabels,
    TopicTable,
    _counts_from,
    _keyword_pattern,
    _resolve_word_counts,
    _thoughts_html,
    _thoughts_md,
    _truncate,
    find_thoughts,
    find_thoughts_html,
    frex,
    label_topics,
    mmr,
    prepare_pyldavis,
    relevance,
    topic_correlation,
    topic_table,
    topics_for_term,
)

from .evaluate import (  # noqa: F401
    AlignmentResult,
    Heldout,
    HeldoutResult,
    ResidualCheck,
    TopicDendrogram,
    _SPLIT_BG_QUANTILE,
    _SPLIT_GAP,
    _accepts_kwarg,
    _chisq_sf,
    _classify_alignment,
    _co_partners,
    _doctopic_corr_matrix,
    _emd_similarity,
    _gammq,
    _hungarian,
    _is_per_doc,
    _kl,
    _split_background,
    _take_rows,
    _topic_hellinger_matrix,
    _topic_js_matrix,
    _transform_theta,
    align_topics,
    bootstrap_stability,
    check_residuals,
    diagnostics,
    document_residuals,
    eval_heldout,
    flag_topics,
    make_heldout,
    perplexity,
    topic_dendrogram,
    topic_stability,
)

__all__ = [
    'AlignmentResult',
    'BestKExplanation',
    'Heldout',
    'HeldoutResult',
    'PyLDAvisInputs',
    'ResidualCheck',
    'SEARCH_K_DIRECTIONS',
    'SearchKResult',
    'SelectModelResult',
    'TopicCorrelation',
    'TopicDendrogram',
    'TopicLabels',
    'TopicTable',
    'align_topics',
    'bootstrap_stability',
    'check_residuals',
    'diagnostics',
    'document_residuals',
    'eval_heldout',
    'find_thoughts',
    'find_thoughts_html',
    'flag_topics',
    'frex',
    'label_topics',
    'make_heldout',
    'mmr',
    'perplexity',
    'plot_models',
    'plot_search_k',
    'plot_topic_discovery',
    'prepare_pyldavis',
    'quality_frontier',
    'relevance',
    'search_k',
    'select_model',
    'topic_correlation',
    'topic_dendrogram',
    'topic_stability',
    'topic_table',
    'topics_for_term',
]
